### ISSUE TITLE
your citibike project is not loading correctly. 

### ISSUE THREAD

**Issue by fedhere** [rachelsmc/PUI2018_rms818#3]
You have 2 pull requests, Please accept them! Those are the reviews your classmates did of your project!

Also your citibike project is currently not loading correctly. Please check

https://github.com/rachelsmc/PUI2018_rms818/blob/master/HW4_rms818/Assignment%202.ipynb

**Comment by rachelsmc** [comment]
Hi Dr. Bianco, sorry about pull requests, I have accepted them.

I ran the notebook again and it worked but it took a while for the download to take place. I am planning to replace 'curl -O' with 'wget', should I just go ahead?

Thanks!

**Comment by fedhere** [comment]
Hi, good on accepting the pull requests. The code is fine: there was a GitHub issue yesterday and it was not rendering on my browser
